# Generated by Django 5.2.7 on 2025-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='special',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
    ]
