# Generated by Django 5.2.7 on 2025-10-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_article_summary_article_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آموزش')),
                ('video', models.FileField(upload_to='courses/videos/', verbose_name='ویدئو')),
                ('special', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
