# Generated by Django 5.2.7 on 2025-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='نامک (Slug)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='نامک (Slug)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='نامک (Slug)'),
            preserve_default=False,
        ),
    ]
