# Generated by Django 5.2.7 on 2025-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_article_slug_course_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default=1, help_text="ویژگی\u200cها را با '|' جدا کنید. حداکثر ۹ ویژگی.", verbose_name='ویژگی\u200cها'),
            preserve_default=False,
        ),
    ]
