# Generated by Django 5.2.7 on 2025-11-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع فاکتور')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('image', models.URLField(blank=True, null=True, verbose_name='تصویر محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.order', verbose_name='سفارش')),
            ],
        ),
    ]
