# Generated by Django 5.2.7 on 2025-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
